const express = require('express');
const router = express.Router();
const mysql = require('mysql');
const request = require('request-promise-lite')
const  async   = require('async');

const connection = mysql.createConnection({host: "db-instance-001.cr2mkf8dawuj.us-east-2.rds.amazonaws.com", user: "coldplay", password: "i took out of the password",
});

const all_cols = '_STATE  DECIMAL(12,1) DEFAULT NULL,_GEOSTR  DECIMAL(12,1) DEFAULT NULL,_DENSTR2  DECIMAL(12,1) DEFAULT NULL,PRECALL  DECIMAL(12,1) DEFAULT NULL,REPNUM  DECIMAL(12,1) DEFAULT NULL,REPDEPTH  DECIMAL(12,1) DEFAULT NULL,FMONTH  DECIMAL(12,1) DEFAULT NULL,DISPCODE  DECIMAL(12,1) DEFAULT NULL,SEQNO  DECIMAL(12,1) DEFAULT NULL,_PSU  DECIMAL(12,1) DEFAULT NULL,NATTMPTS  DECIMAL(12,1) DEFAULT NULL,' +
    'NRECSEL  DECIMAL(12,1) DEFAULT NULL,NRECSTR  DECIMAL(12,1) DEFAULT NULL,CTELENUM  DECIMAL(12,1) DEFAULT NULL,CELLFON  DECIMAL(12,1) DEFAULT NULL,PVTRESID  DECIMAL(12,1) DEFAULT NULL,NUMADULT  DECIMAL(12,1) DEFAULT NULL,NUMMEN  DECIMAL(12,1) DEFAULT NULL,NUMWOMEN  DECIMAL(12,1) DEFAULT NULL,GENHLTH  DECIMAL(12,1) DEFAULT NULL,PHYSHLTH  DECIMAL(12,1) DEFAULT NULL,MENTHLTH  DECIMAL(12,1) DEFAULT NULL,POORHLTH  DECIMAL(12,1) DEFAULT NULL,HLTHPLN1  DECIMAL(12,1) DEFAULT NULL,' +
    'PERSDOC2  DECIMAL(12,1) DEFAULT NULL,MEDCOST  DECIMAL(12,1) DEFAULT NULL,CHECKUP1  DECIMAL(12,1) DEFAULT NULL,BPHIGH4  DECIMAL(12,1) DEFAULT NULL,BPMEDS  DECIMAL(12,1) DEFAULT NULL,BLOODCHO  DECIMAL(12,1) DEFAULT NULL,CHOLCHK  DECIMAL(12,1) DEFAULT NULL,TOLDHI2  DECIMAL(12,1) DEFAULT NULL,CVDINFR4  DECIMAL(12,1) DEFAULT NULL,CVDCRHD4  DECIMAL(12,1) DEFAULT NULL,CVDSTRK3  DECIMAL(12,1) DEFAULT NULL,ASTHMA3  DECIMAL(12,1) DEFAULT NULL,ASTHNOW  DECIMAL(12,1) DEFAULT NULL,' +
    'CHCSCNCR  DECIMAL(12,1) DEFAULT NULL,CHCOCNCR  DECIMAL(12,1) DEFAULT NULL,CHCCOPD  DECIMAL(12,1) DEFAULT NULL,HAVARTH3  DECIMAL(12,1) DEFAULT NULL,ADDEPEV2  DECIMAL(12,1) DEFAULT NULL,CHCKIDNY  DECIMAL(12,1) DEFAULT NULL,CHCVISON  DECIMAL(12,1) DEFAULT NULL,DIABETE3  DECIMAL(12,1) DEFAULT NULL,SMOKE100  DECIMAL(12,1) DEFAULT NULL,SMOKDAY2  DECIMAL(12,1) DEFAULT NULL,STOPSMK2  DECIMAL(12,1) DEFAULT NULL,LASTSMK2  DECIMAL(12,1) DEFAULT NULL,USENOW3  DECIMAL(12,1) DEFAULT NULL,' +
    'AGE  DECIMAL(12,1) DEFAULT NULL,HISPANC2  DECIMAL(12,1) DEFAULT NULL,ORACE2  DECIMAL(12,1) DEFAULT NULL,VETERAN3  DECIMAL(12,1) DEFAULT NULL,MARITAL  DECIMAL(12,1) DEFAULT NULL,CHILDREN  DECIMAL(12,1) DEFAULT NULL,EDUCA  DECIMAL(12,1) DEFAULT NULL,EMPLOY  DECIMAL(12,1) DEFAULT NULL,INCOME2  DECIMAL(12,1) DEFAULT NULL,WEIGHT2  DECIMAL(12,1) DEFAULT NULL,HEIGHT3  DECIMAL(12,1) DEFAULT NULL,CTYCODE1  DECIMAL(12,1) DEFAULT NULL,NUMHHOL2  DECIMAL(12,1) DEFAULT NULL,NUMPHON2  DECIMAL(12,1) DEFAULT NULL,' +
    'CPDEMO1  DECIMAL(12,1) DEFAULT NULL,CPDEMO2  DECIMAL(12,1) DEFAULT NULL,CPDEMO3  DECIMAL(12,1) DEFAULT NULL,CPDEMO4  DECIMAL(12,1) DEFAULT NULL,RENTHOM1  DECIMAL(12,1) DEFAULT NULL,SEX  DECIMAL(12,1) DEFAULT NULL,PREGNANT  DECIMAL(12,1) DEFAULT NULL,FRUITJU1  DECIMAL(12,1) DEFAULT NULL,FRUIT1  DECIMAL(12,1) DEFAULT NULL,FVBEANS  DECIMAL(12,1) DEFAULT NULL,FVGREEN  DECIMAL(12,1) DEFAULT NULL,FVORANG  DECIMAL(12,1) DEFAULT NULL,VEGETAB1  DECIMAL(12,1) DEFAULT NULL,EXERANY2  DECIMAL(12,1) DEFAULT NULL,EXRACT01  DECIMAL(12,1) DEFAULT NULL,' +
    'EXEROFT1  DECIMAL(12,1) DEFAULT NULL,EXERHMM1  DECIMAL(12,1) DEFAULT NULL,EXRACT02  DECIMAL(12,1) DEFAULT NULL,EXEROFT2  DECIMAL(12,1) DEFAULT NULL,EXERHMM2  DECIMAL(12,1) DEFAULT NULL,STRENGTH  DECIMAL(12,1) DEFAULT NULL,QLACTLM2  DECIMAL(12,1) DEFAULT NULL,USEEQUIP  DECIMAL(12,1) DEFAULT NULL,LMTJOIN3  DECIMAL(12,1) DEFAULT NULL,ARTHDIS2  DECIMAL(12,1) DEFAULT NULL,ARTHSOCL  DECIMAL(12,1) DEFAULT NULL,JOINPAIN  DECIMAL(12,1) DEFAULT NULL,SEATBELT  DECIMAL(12,1) DEFAULT NULL,' +
    'FLUSHOT5  DECIMAL(12,1) DEFAULT NULL,FLSHTMY2  DECIMAL(12,1) DEFAULT NULL,IMFVPLAC  DECIMAL(12,1) DEFAULT NULL,PNEUVAC3  DECIMAL(12,1) DEFAULT NULL,ALCDAY5  DECIMAL(12,1) DEFAULT NULL,AVEDRNK2  DECIMAL(12,1) DEFAULT NULL,DRNK3GE5  DECIMAL(12,1) DEFAULT NULL,MAXDRNKS  DECIMAL(12,1) DEFAULT NULL,HIVTST6  DECIMAL(12,1) DEFAULT NULL,HIVTSTD3  DECIMAL(12,1) DEFAULT NULL,HIVRISK3  DECIMAL(12,1) DEFAULT NULL,PDIABTST  DECIMAL(12,1) DEFAULT NULL,PREDIAB1  DECIMAL(12,1) DEFAULT NULL,' +
    'DIABAGE2  DECIMAL(12,1) DEFAULT NULL,INSULIN  DECIMAL(12,1) DEFAULT NULL,BLDSUGAR  DECIMAL(12,1) DEFAULT NULL,FEETCHK2  DECIMAL(12,1) DEFAULT NULL,DOCTDIAB  DECIMAL(12,1) DEFAULT NULL,CHKHEMO3  DECIMAL(12,1) DEFAULT NULL,FEETCHK  DECIMAL(12,1) DEFAULT NULL,EYEEXAM  DECIMAL(12,1) DEFAULT NULL,DIABEYE  DECIMAL(12,1) DEFAULT NULL,DIABEDU  DECIMAL(12,1) DEFAULT NULL,PAINACT2  DECIMAL(12,1) DEFAULT NULL,QLMENTL2  DECIMAL(12,1) DEFAULT NULL,QLSTRES2  DECIMAL(12,1) DEFAULT NULL,QLHLTH2  DECIMAL(12,1) DEFAULT NULL,' +
    'SSBSUGAR  DECIMAL(12,1) DEFAULT NULL,SSBFRUIT  DECIMAL(12,1) DEFAULT NULL,SSBCALRI  DECIMAL(12,1) DEFAULT NULL,PFPPREPR  DECIMAL(12,1) DEFAULT NULL,PFPPRGNT  DECIMAL(12,1) DEFAULT NULL,PFPPRVNT  DECIMAL(12,1) DEFAULT NULL,TYPCNTR6  DECIMAL(12,1) DEFAULT NULL,NOBCUSE4  DECIMAL(12,1) DEFAULT NULL,FPCHLDF2  DECIMAL(12,1) DEFAULT NULL,PFPVITMN  DECIMAL(12,1) DEFAULT NULL,VIDFCLT3  DECIMAL(12,1) DEFAULT NULL,VIREDIF3  DECIMAL(12,1) DEFAULT NULL,VIPRFVS3  DECIMAL(12,1) DEFAULT NULL,' +
    'VINOCRE3  DECIMAL(12,1) DEFAULT NULL,VIEYEXM3  DECIMAL(12,1) DEFAULT NULL,VIINSUR3  DECIMAL(12,1) DEFAULT NULL,VICTRCT3  DECIMAL(12,1) DEFAULT NULL,VIGLUMA3  DECIMAL(12,1) DEFAULT NULL,VIMACDG3  DECIMAL(12,1) DEFAULT NULL,QLREST2  DECIMAL(12,1) DEFAULT NULL,SLEPTIME  DECIMAL(12,1) DEFAULT NULL,SLEPSNOR  DECIMAL(12,1) DEFAULT NULL,SLEPDAY  DECIMAL(12,1) DEFAULT NULL,SLEPDRIV  DECIMAL(12,1) DEFAULT NULL,WRKHCF1  DECIMAL(12,1) DEFAULT NULL,DIRCONT1  DECIMAL(12,1) DEFAULT NULL,DRHPAD1  DECIMAL(12,1) DEFAULT NULL,' +
    'HAREHAB1  DECIMAL(12,1) DEFAULT NULL,STREHAB1  DECIMAL(12,1) DEFAULT NULL,CVDASPRN  DECIMAL(12,1) DEFAULT NULL,ASPUNSAF  DECIMAL(12,1) DEFAULT NULL,BPEATHBT  DECIMAL(12,1) DEFAULT NULL,BPSALT  DECIMAL(12,1) DEFAULT NULL,BPALCHOL  DECIMAL(12,1) DEFAULT NULL,BPEXER  DECIMAL(12,1) DEFAULT NULL,BPEATADV  DECIMAL(12,1) DEFAULT NULL,BPSLTADV  DECIMAL(12,1) DEFAULT NULL,BPALCADV  DECIMAL(12,1) DEFAULT NULL,BPEXRADV  DECIMAL(12,1) DEFAULT NULL,BPMEDADV  DECIMAL(12,1) DEFAULT NULL,BPHI2MR  DECIMAL(12,1) DEFAULT NULL,' +
    'HASYMP1  DECIMAL(12,1) DEFAULT NULL,HASYMP2  DECIMAL(12,1) DEFAULT NULL,HASYMP3  DECIMAL(12,1) DEFAULT NULL,HASYMP4  DECIMAL(12,1) DEFAULT NULL,HASYMP5  DECIMAL(12,1) DEFAULT NULL,HASYMP6  DECIMAL(12,1) DEFAULT NULL,STRSYMP1  DECIMAL(12,1) DEFAULT NULL,STRSYMP2  DECIMAL(12,1) DEFAULT NULL,STRSYMP3  DECIMAL(12,1) DEFAULT NULL,STRSYMP4  DECIMAL(12,1) DEFAULT NULL,STRSYMP5  DECIMAL(12,1) DEFAULT NULL,STRSYMP6  DECIMAL(12,1) DEFAULT NULL,FIRSTAID  DECIMAL(12,1) DEFAULT NULL,HADMAM  DECIMAL(12,1) DEFAULT NULL,' +
    'HOWLONG  DECIMAL(12,1) DEFAULT NULL,PROFEXAM  DECIMAL(12,1) DEFAULT NULL,LENGEXAM  DECIMAL(12,1) DEFAULT NULL,HADPAP2  DECIMAL(12,1) DEFAULT NULL,LASTPAP2  DECIMAL(12,1) DEFAULT NULL,HADHYST2  DECIMAL(12,1) DEFAULT NULL,PCPSAREC  DECIMAL(12,1) DEFAULT NULL,PSATEST1  DECIMAL(12,1) DEFAULT NULL,PSATIME  DECIMAL(12,1) DEFAULT NULL,PCPSARSN  DECIMAL(12,1) DEFAULT NULL,PCPSAADV  DECIMAL(12,1) DEFAULT NULL,PCPSADIS  DECIMAL(12,1) DEFAULT NULL,PCPSADEC  DECIMAL(12,1) DEFAULT NULL,' +
    'PROSTATE  DECIMAL(12,1) DEFAULT NULL,BLDSTOOL  DECIMAL(12,1) DEFAULT NULL,LSTBLDS3  DECIMAL(12,1) DEFAULT NULL,HADSIGM3  DECIMAL(12,1) DEFAULT NULL,HADSGCO1  DECIMAL(12,1) DEFAULT NULL,LASTSIG3  DECIMAL(12,1) DEFAULT NULL,SMCQUITL  DECIMAL(12,1) DEFAULT NULL,SMCTRYQT  DECIMAL(12,1) DEFAULT NULL,SMCCALQT  DECIMAL(12,1) DEFAULT NULL,SMCPROGQ  DECIMAL(12,1) DEFAULT NULL,SMCCNSLQ  DECIMAL(12,1) DEFAULT NULL,SMCMEDQT  DECIMAL(12,1) DEFAULT NULL,SMCTIMEQ  DECIMAL(12,1) DEFAULT NULL,' +
    'SMCPLANQ  DECIMAL(12,1) DEFAULT NULL,SHSNWRK1  DECIMAL(12,1) DEFAULT NULL,SHSNHOM1  DECIMAL(12,1) DEFAULT NULL,SHSRIDEV  DECIMAL(12,1) DEFAULT NULL,SHSINPUB  DECIMAL(12,1) DEFAULT NULL,SHSHOMES  DECIMAL(12,1) DEFAULT NULL,SHSVHICL  DECIMAL(12,1) DEFAULT NULL,SHSALOW1  DECIMAL(12,1) DEFAULT NULL,ASTHMAGE  DECIMAL(12,1) DEFAULT NULL,ASATTACK  DECIMAL(12,1) DEFAULT NULL,ASERVIST  DECIMAL(12,1) DEFAULT NULL,ASDRVIST  DECIMAL(12,1) DEFAULT NULL,ASRCHKUP  DECIMAL(12,1) DEFAULT NULL,' +
    'ASACTLIM  DECIMAL(12,1) DEFAULT NULL,ASYMPTOM  DECIMAL(12,1) DEFAULT NULL,ASNOSLEP  DECIMAL(12,1) DEFAULT NULL,ASTHMED3  DECIMAL(12,1) DEFAULT NULL,ASINHALR  DECIMAL(12,1) DEFAULT NULL,ARTTODAY  DECIMAL(12,1) DEFAULT NULL,ARTHWGT  DECIMAL(12,1) DEFAULT NULL,ARTHEXER  DECIMAL(12,1) DEFAULT NULL,ARTHEDU  DECIMAL(12,1) DEFAULT NULL,TNSARCV  DECIMAL(12,1) DEFAULT NULL,TNSARCNT  DECIMAL(12,1) DEFAULT NULL,TNSASHT1  DECIMAL(12,1) DEFAULT NULL,HPVADVC2  DECIMAL(12,1) DEFAULT NULL,' +
    'HPVADSHT  DECIMAL(12,1) DEFAULT NULL,SHINGLE1  DECIMAL(12,1) DEFAULT NULL,COPDTEST  DECIMAL(12,1) DEFAULT NULL,COPDQOL  DECIMAL(12,1) DEFAULT NULL,COPDDOC  DECIMAL(12,1) DEFAULT NULL,COPDHOSP  DECIMAL(12,1) DEFAULT NULL,COPDMEDS  DECIMAL(12,1) DEFAULT NULL,GPWELPR3  DECIMAL(12,1) DEFAULT NULL,GP3DYWTR  DECIMAL(12,1) DEFAULT NULL,GP3DYFD1  DECIMAL(12,1) DEFAULT NULL,GP3DYPRS  DECIMAL(12,1) DEFAULT NULL,GPBATRAD  DECIMAL(12,1) DEFAULT NULL,GPFLSLIT  DECIMAL(12,1) DEFAULT NULL,GPEMRCM1  DECIMAL(12,1) DEFAULT NULL,' +
    'GPEMRIN1  DECIMAL(12,1) DEFAULT NULL,GPVACPL1  DECIMAL(12,1) DEFAULT NULL,GPMNDEVC  DECIMAL(12,1) DEFAULT NULL,GPNOTEV1  DECIMAL(12,1) DEFAULT NULL,VHCOMBAT  DECIMAL(12,1) DEFAULT NULL,VHDRPTSD  DECIMAL(12,1) DEFAULT NULL,VHDRTBI  DECIMAL(12,1) DEFAULT NULL,VHCOUNSL  DECIMAL(12,1) DEFAULT NULL,VHTAKLIF  DECIMAL(12,1) DEFAULT NULL,VHSUICID  DECIMAL(12,1) DEFAULT NULL,RRCLASS2  DECIMAL(12,1) DEFAULT NULL,RRCOGNT2  DECIMAL(12,1) DEFAULT NULL,RRATWRK2  DECIMAL(12,1) DEFAULT NULL,RRHCARE3  DECIMAL(12,1) DEFAULT NULL,' +
    'RRPHYSM2  DECIMAL(12,1) DEFAULT NULL,RREMTSM2  DECIMAL(12,1) DEFAULT NULL,ADPLEASR  DECIMAL(12,1) DEFAULT NULL,ADDOWN  DECIMAL(12,1) DEFAULT NULL,ADSLEEP  DECIMAL(12,1) DEFAULT NULL,ADENERGY  DECIMAL(12,1) DEFAULT NULL,ADEAT1  DECIMAL(12,1) DEFAULT NULL,ADFAIL  DECIMAL(12,1) DEFAULT NULL,ADTHINK  DECIMAL(12,1) DEFAULT NULL,ADMOVE  DECIMAL(12,1) DEFAULT NULL,MISTMNT  DECIMAL(12,1) DEFAULT NULL,ADANXEV  DECIMAL(12,1) DEFAULT NULL,CIMEMLOS  DECIMAL(12,1) DEFAULT NULL,CINOADLT  DECIMAL(12,1) DEFAULT NULL,CIRBIAGE  DECIMAL(12,1) DEFAULT NULL,' +
    'CIHOWOFT  DECIMAL(12,1) DEFAULT NULL,CIASSIST  DECIMAL(12,1) DEFAULT NULL,CIINTFER  DECIMAL(12,1) DEFAULT NULL,CIFAMCAR  DECIMAL(12,1) DEFAULT NULL,CIHCPROF  DECIMAL(12,1) DEFAULT NULL,CIMEDS  DECIMAL(12,1) DEFAULT NULL,CIDIAGAZ  DECIMAL(12,1) DEFAULT NULL,SCNTMONY  DECIMAL(12,1) DEFAULT NULL,SCNTMEAL  DECIMAL(12,1) DEFAULT NULL,SCNTPAID  DECIMAL(12,1) DEFAULT NULL,SCNTWRK1  DECIMAL(12,1) DEFAULT NULL,SCNTLPAD  DECIMAL(12,1) DEFAULT NULL,SCNTLWK1  DECIMAL(12,1) DEFAULT NULL,WHRTST9  DECIMAL(12,1) DEFAULT NULL,' +
    'HIVRDTS2  DECIMAL(12,1) DEFAULT NULL,EMTSUPRT  DECIMAL(12,1) DEFAULT NULL,LSATISFY  DECIMAL(12,1) DEFAULT NULL,ACEDEPRS  DECIMAL(12,1) DEFAULT NULL,ACEDRINK  DECIMAL(12,1) DEFAULT NULL,ACEDRUGS  DECIMAL(12,1) DEFAULT NULL,ACEPRISN  DECIMAL(12,1) DEFAULT NULL,ACEDIVRC  DECIMAL(12,1) DEFAULT NULL,ACEPUNCH  DECIMAL(12,1) DEFAULT NULL,ACEHURT  DECIMAL(12,1) DEFAULT NULL,ACESWEAR  DECIMAL(12,1) DEFAULT NULL,ACETOUCH  DECIMAL(12,1) DEFAULT NULL,ACETTHEM  DECIMAL(12,1) DEFAULT NULL,ACEHVSEX  DECIMAL(12,1) DEFAULT NULL,' +
    'RCSGENDR  DECIMAL(12,1) DEFAULT NULL,RCHISLAT  DECIMAL(12,1) DEFAULT NULL,RCSBRACE  DECIMAL(12,1) DEFAULT NULL,RCSRLTN2  DECIMAL(12,1) DEFAULT NULL,CASTHDX2  DECIMAL(12,1) DEFAULT NULL,CASTHNO2  DECIMAL(12,1) DEFAULT NULL,FLUSHCH2  DECIMAL(12,1) DEFAULT NULL,CHIMRCVE  DECIMAL(12,1) DEFAULT NULL,CALLBACK  DECIMAL(12,1) DEFAULT NULL,ADLTCHLD  DECIMAL(12,1) DEFAULT NULL,CTELNUM1  DECIMAL(12,1) DEFAULT NULL,' +
    'CELLFON2  DECIMAL(12,1) DEFAULT NULL,CADULT  DECIMAL(12,1) DEFAULT NULL,PVTRESD2  DECIMAL(12,1) DEFAULT NULL,CSTATE  DECIMAL(12,1) DEFAULT NULL,RSPSTATE  DECIMAL(12,1) DEFAULT NULL,LANDLINE  DECIMAL(12,1) DEFAULT NULL,PCTCELL  DECIMAL(12,1) DEFAULT NULL,QSTVER  DECIMAL(12,1) DEFAULT NULL,QSTLANG  DECIMAL(12,1) DEFAULT NULL,MSCODE  DECIMAL(12,1) DEFAULT NULL,_STSTR  DECIMAL(12,1) DEFAULT NULL,_STRWT  DECIMAL(12,1) DEFAULT NULL,_RAW  DECIMAL(12,1) DEFAULT NULL,_WT2  DECIMAL(12,1) DEFAULT NULL,_RAWRAKE  DECIMAL(12,1) DEFAULT NULL,_WT2RAKE  DECIMAL(12,1) DEFAULT NULL,' +
    '_REGION  DECIMAL(12,1) DEFAULT NULL,_IMPAGE  DECIMAL(12,1) DEFAULT NULL,_IMPRACE  DECIMAL(12,1) DEFAULT NULL,_IMPNPH  DECIMAL(12,1) DEFAULT NULL,O_STATE  DECIMAL(12,1) DEFAULT NULL,CRACEASC  DECIMAL(12,1) DEFAULT NULL,_CRACE  DECIMAL(12,1) DEFAULT NULL,_RAWCH  DECIMAL(12,1) DEFAULT NULL,_WT2CH  DECIMAL(12,1) DEFAULT NULL,CHILDAGE  DECIMAL(12,1) DEFAULT NULL,_CLCPM01  DECIMAL(12,1) DEFAULT NULL,_CLCPM02  DECIMAL(12,1) DEFAULT NULL,_CLCPM03  DECIMAL(12,1) DEFAULT NULL,_CLCPM04  DECIMAL(12,1) DEFAULT NULL,_CLCPM05  DECIMAL(12,1) DEFAULT NULL,' +
    '_CLLCPWT  DECIMAL(12,1) DEFAULT NULL,_LLCPM01  DECIMAL(12,1) DEFAULT NULL,_LLCPM02  DECIMAL(12,1) DEFAULT NULL,_LLCPM03  DECIMAL(12,1) DEFAULT NULL,_LLCPM04  DECIMAL(12,1) DEFAULT NULL,_LLCPM05  DECIMAL(12,1) DEFAULT NULL,_LLCPM06  DECIMAL(12,1) DEFAULT NULL,_LLCPM07  DECIMAL(12,1) DEFAULT NULL,_LLCPM08  DECIMAL(12,1) DEFAULT NULL,_LLCPM09  DECIMAL(12,1) DEFAULT NULL,_LLCPM10  DECIMAL(12,1) DEFAULT NULL,_LLCPM11  DECIMAL(12,1) DEFAULT NULL,_LLCPM12  DECIMAL(12,1) DEFAULT NULL,_LLCPWT  DECIMAL(12,1) DEFAULT NULL,' +
    '_RFHLTH  DECIMAL(12,1) DEFAULT NULL,_HCVU651  DECIMAL(12,1) DEFAULT NULL,_RFHYPE5  DECIMAL(12,1) DEFAULT NULL,_CHOLCHK  DECIMAL(12,1) DEFAULT NULL,_RFCHOL  DECIMAL(12,1) DEFAULT NULL,_LTASTH1  DECIMAL(12,1) DEFAULT NULL,_CASTHM1  DECIMAL(12,1) DEFAULT NULL,_ASTHMS1  DECIMAL(12,1) DEFAULT NULL,_DRDXAR1  DECIMAL(12,1) DEFAULT NULL,_SMOKER3  DECIMAL(12,1) DEFAULT NULL,_RFSMOK3  DECIMAL(12,1) DEFAULT NULL,MRACEASC  DECIMAL(12,1) DEFAULT NULL,_PRACE  DECIMAL(12,1) DEFAULT NULL,' +
    '_MRACE  DECIMAL(12,1) DEFAULT NULL,RACE2  DECIMAL(12,1) DEFAULT NULL,_RACEG2  DECIMAL(12,1) DEFAULT NULL,_RACEGR2  DECIMAL(12,1) DEFAULT NULL,_RACE_G  DECIMAL(12,1) DEFAULT NULL,_CNRACE  DECIMAL(12,1) DEFAULT NULL,_CNRACEC  DECIMAL(12,1) DEFAULT NULL,_AGEG5YR  DECIMAL(12,1) DEFAULT NULL,_AGE65YR  DECIMAL(12,1) DEFAULT NULL,_AGE_G  DECIMAL(12,1) DEFAULT NULL,HTIN4  DECIMAL(12,1) DEFAULT NULL,HTM4  DECIMAL(12,1) DEFAULT NULL,WTKG3  DECIMAL(12,1) DEFAULT NULL,_BMI5  DECIMAL(12,1) DEFAULT NULL,_BMI5CAT  DECIMAL(12,1) DEFAULT NULL,_RFBMI5  DECIMAL(12,1) DEFAULT NULL,_CHLDCNT  DECIMAL(12,1) DEFAULT NULL,' +
    '_EDUCAG  DECIMAL(12,1) DEFAULT NULL,_INCOMG  DECIMAL(12,1) DEFAULT NULL,FTJUDA1_  DECIMAL(12,1) DEFAULT NULL,FRUTDA1_  DECIMAL(12,1) DEFAULT NULL,BEANDAY_  DECIMAL(12,1) DEFAULT NULL,GRENDAY_  DECIMAL(12,1) DEFAULT NULL,ORNGDAY_  DECIMAL(12,1) DEFAULT NULL,VEGEDA1_  DECIMAL(12,1) DEFAULT NULL,_MISFRTN  DECIMAL(12,1) DEFAULT NULL,_MISVEGN  DECIMAL(12,1) DEFAULT NULL,_FRTRESP  DECIMAL(12,1) DEFAULT NULL,_VEGRESP  DECIMAL(12,1) DEFAULT NULL,_FRUTSUM  DECIMAL(12,1) DEFAULT NULL,_VEGESUM  DECIMAL(12,1) DEFAULT NULL,' +
    '_FRT16  DECIMAL(12,1) DEFAULT NULL,_VEG23  DECIMAL(12,1) DEFAULT NULL,_FRUITEX  DECIMAL(12,1) DEFAULT NULL,_VEGETEX  DECIMAL(12,1) DEFAULT NULL,_TOTINDA  DECIMAL(12,1) DEFAULT NULL,METVAL1_  DECIMAL(12,1) DEFAULT NULL,METVAL2_  DECIMAL(12,1) DEFAULT NULL,MAXVO2_  DECIMAL(12,1) DEFAULT NULL,FC60_  DECIMAL(12,1) DEFAULT NULL,ACTINT1_  DECIMAL(12,1) DEFAULT NULL,ACTINT2_  DECIMAL(12,1) DEFAULT NULL,PADUR1_  DECIMAL(12,1) DEFAULT NULL,PADUR2_  DECIMAL(12,1) DEFAULT NULL,PAFREQ1_  DECIMAL(12,1) DEFAULT NULL,PAFREQ2_  DECIMAL(12,1) DEFAULT NULL,' +
    '_MINACT1  DECIMAL(12,1) DEFAULT NULL,_MINACT2  DECIMAL(12,1) DEFAULT NULL,STRFREQ_  DECIMAL(12,1) DEFAULT NULL,PAMISS_  DECIMAL(12,1) DEFAULT NULL,PAMIN1_  DECIMAL(12,1) DEFAULT NULL,PAMIN2_  DECIMAL(12,1) DEFAULT NULL,PAMIN_  DECIMAL(12,1) DEFAULT NULL,PAVIGM1_  DECIMAL(12,1) DEFAULT NULL,PAVIGM2_  DECIMAL(12,1) DEFAULT NULL,PAVIGMN_  DECIMAL(12,1) DEFAULT NULL,_PACAT  DECIMAL(12,1) DEFAULT NULL,_PAINDEX  DECIMAL(12,1) DEFAULT NULL,_PA150R1  DECIMAL(12,1) DEFAULT NULL,_PA300R1  DECIMAL(12,1) DEFAULT NULL,_PA3002L  DECIMAL(12,1) DEFAULT NULL,' +
    '_PASTRNG  DECIMAL(12,1) DEFAULT NULL,_PAREC  DECIMAL(12,1) DEFAULT NULL,_PASTAER  DECIMAL(12,1) DEFAULT NULL,_RFSEAT2  DECIMAL(12,1) DEFAULT NULL,_RFSEAT3  DECIMAL(12,1) DEFAULT NULL,_FLSHOT5  DECIMAL(12,1) DEFAULT NULL,_PNEUMO2  DECIMAL(12,1) DEFAULT NULL,DRNKANY5  DECIMAL(12,1) DEFAULT NULL,DROCDY3_  DECIMAL(12,1) DEFAULT NULL,_RFBING5  DECIMAL(12,1) DEFAULT NULL,_DRNKDY4  DECIMAL(12,1) DEFAULT NULL,_DRNKMO4  DECIMAL(12,1) DEFAULT NULL,_RFDRHV4  DECIMAL(12,1) DEFAULT NULL,_RFDRMN4  DECIMAL(12,1) DEFAULT NULL,' +
    '_RFDRWM4  DECIMAL(12,1) DEFAULT NULL,_AIDTST3  DECIMAL(12,1) DEFAULT NULL,HAVHPAD DECIMAL(12,1) DEFAULT NULL';

//Query for creating the mega table
const mega_table = "CREATE TABLE mega (" + all_cols+ ");";
const create_db  = "CREATE DATABASE IF NOT EXISTS project2";
// const use_db     = "USE project2";


//Establish the AWS RDS MYSQL connection
// connection.connect(function(err) {
//     if (err) throw err;
//     console.log("...........");
//     console.log("Successfully Connected To AWS MYSQL SERVER!!!!!!!!!");
//     console.log("...........");
//
//     //execute query.................
//     console.log("CREATE DATABASE");
//     connection.query(create_db);
//
//     console.log("USE DATABASE");
//     connection.query(use_db);
//
//     console.log("CREATE TABLE mega");
//     connection.query(mega_table,function(error,result,fields){console.log(result)});
//
//     connection.end();
// })


router.get('/CA', function (req, res) {
    const pool = mysql.createPool({host: "db-instance-001.cr2mkf8dawuj.us-east-2.rds.amazonaws.com", user: "coldplay", password: "i took out of the password",connectionLimit: 10,});
    var query1 = "use project"
    var query2 = "use project; call california()";

    var return_data = {};

    async.parallel([
        function(parallel_done) {
            pool.query(query1, {}, function(err, results) {
                if (err) return parallel_done(err);
                return_data.table1 = results;
                parallel_done();
            });
        },
        function(parallel_done) {
            pool.query(query2, {}, function(err, results) {
                if (err) return parallel_done(err);
                return_data.table2 = results;
                parallel_done();
            });
        }
    ], function(err) {
        if (err) console.log(err);
        connection.end();
        console.log(return_data);
        res.send(return_data);
    });
});



router.get('/CAoverweight', function (req, res) {
    const pool = mysql.createPool({host: "db-instance-001.cr2mkf8dawuj.us-east-2.rds.amazonaws.com", user: "coldplay", password: "i took out of the password",connectionLimit: 10,});
    var query1 = "use project"
    var query2 = "use project; call california_overweight()";

    var return_data = {};

    async.parallel([
        function(parallel_done) {
            pool.query(query1, {}, function(err, results) {
                if (err) return parallel_done(err);
                return_data.table1 = results;
                parallel_done();
            });
        },
        function(parallel_done) {
            pool.query(query2, {}, function(err, results) {
                if (err) return parallel_done(err);
                return_data.table2 = results;
                parallel_done();
            });
        }
    ], function(err) {
        if (err) console.log(err);
        connection.end();
        console.log(return_data);
        res.send(return_data);
    });
});


router.get('/TN', function (req, res) {
    const pool = mysql.createPool({host: "db-instance-001.cr2mkf8dawuj.us-east-2.rds.amazonaws.com", user: "coldplay", password: "i took out of the password",connectionLimit: 10,});
    var query1 = "use project"
    var query2 = "use project; call tennessee()";

    var return_data = {};

    async.parallel([
        function(parallel_done) {
            pool.query(query1, {}, function(err, results) {
                if (err) return parallel_done(err);
                return_data.table1 = results;
                parallel_done();
            });
        },
        function(parallel_done) {
            pool.query(query2, {}, function(err, results) {
                if (err) return parallel_done(err);
                return_data.table2 = results;
                parallel_done();
            });
        }
    ], function(err) {
        if (err) console.log(err);
        connection.end();
        console.log(return_data);
        res.send(return_data);
    });
});



router.get('/TNoverweight', function (req, res) {
    const pool = mysql.createPool({host: "db-instance-001.cr2mkf8dawuj.us-east-2.rds.amazonaws.com", user: "coldplay", password: "i took out of the password",connectionLimit: 10,});
    var query1 = "use project"
    var query2 = "use project; call tennessee_overweight()";

    var return_data = {};

    async.parallel([
        function(parallel_done) {
            pool.query(query1, {}, function(err, results) {
                if (err) return parallel_done(err);
                return_data.table1 = results;
                parallel_done();
            });
        },
        function(parallel_done) {
            pool.query(query2, {}, function(err, results) {
                if (err) return parallel_done(err);
                return_data.table2 = results;
                parallel_done();
            });
        }
    ], function(err) {
        if (err) console.log(err);
        connection.end();
        console.log(return_data);
        res.send(return_data);
    });
});




module.exports = router;
